version: 13
services:
# Service MySQL
mysql:
image: mysql:latest
container name: mysql-container!
environment:
MYSQL ROOT PASSWORD: 200t
ports:
  3306:3306
networks:
  microservices-network
#Service Consul
consul:
image: consul:1.15.4
container name: consul-container
ports:
  18500:8500
networks:
  microservices-network
# Service Gateway
gateway-service:
build:
context: /gatewayService
ports:
depends on:
  mysql
  consul
networks:
  microservices-network
environment:
SPRING_CLOUD_CONSUL HOST: consul
SPRING CLOUD CONSUL PORT:
  8500
SPRING CLOUD_CONSUL DISCOVERY ENABLED: 'true'
#Service Client
client-service:
build:
context: ./clientService
ports:
  19088:8068"
depends on:
  mysql
  consul
  gateway-service
networks:
  microservices-network
environment:
SPRING CLOUD CONSUL HOST: consul
SPRING CLOUD CONSUL FORT: 8500
SPRING CLOUD_CONSUL_DISCOVERY ENABLED: 'true'
# Service Client
client-service:
build:
context: ./clientService
ports:
#8088:8088"
depends_on:
  mysql
- consul
  gateway-service
networks:
  - microservices-network
environment:
SPRING CLOUD_CONSUL_HOST: consul
SPRING CLOUD_CONSUL PORT: 8500
SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: 'true'